var imageGal = [
	{galleryimage: 'images/gallery/award_02.jpg', gallerythumb: 'images/gallery/thumbs/award_02_thumb.jpg', gallerycaption: 'National Honor Society Membership'}, 
	{galleryimage: 'images/gallery/award_03.jpg', gallerythumb: 'images/gallery/thumbs/award_03_thumb.jpg', gallerycaption: '2018 BPA SLC: First Place Java Programming Winner'}, 
	{galleryimage: 'images/gallery/award_04.jpg', gallerythumb: 'images/gallery/thumbs/award_04_thumb.jpg', gallerycaption: '2018 BPA SLC: Second Place Fundamentals of Web Design Winner'}, 
	{galleryimage: 'images/gallery/award_05.jpg', gallerythumb: 'images/gallery/thumbs/award_05_thumb.jpg', gallerycaption: '2018 BPA SLC: Third Place Admin Support Team Winner'}, 
	{galleryimage: 'images/gallery/award_06.jpg', gallerythumb: 'images/gallery/thumbs/award_06_thumb.jpg', gallerycaption: '2018 BPA SLC: Diplomat Torch Award Recipient For Membership Service'}, 
	{galleryimage: 'images/gallery/award_07.jpg', gallerythumb: 'images/gallery/thumbs/award_07_thumb.jpg', gallerycaption: '2017 Bear Award Winner For Demonstrating Core Values: Recommended by Laura McLean'}, 
	{galleryimage: 'images/gallery/award_08.jpg', gallerythumb: 'images/gallery/thumbs/award_08_thumb.jpg', gallerycaption: '2017 BPA NLC Workshop Participation Award: How To Land a Job'}, 
	{galleryimage: 'images/gallery/award_09.jpg', gallerythumb: 'images/gallery/thumbs/award_09_thumb.jpg', gallerycaption: '2017 Skills USA District Conference: Computer Programming Participant'}, 
	{galleryimage: 'images/gallery/award_10.jpg', gallerythumb: 'images/gallery/thumbs/award_10_thumb.jpg', gallerycaption: 'Providence College: High School Computer Programming Contest Participant'}, 
	{galleryimage: 'images/gallery/award_11.jpg', gallerythumb: 'images/gallery/thumbs/award_11_thumb.jpg', gallerycaption: '2017 BPA SLC: Executive Torch Award Recipient For Membership Service'}, 
	{galleryimage: 'images/gallery/award_12.jpg', gallerythumb: 'images/gallery/thumbs/award_12_thumb.jpg', gallerycaption: '2017 BPA SLC: First Place Admin Support Team Winner'}, 
	{galleryimage: 'images/gallery/award_14.jpg', gallerythumb: 'images/gallery/thumbs/award_14_thumb.jpg', gallerycaption: '2017 BPA SLC: Fourth Place Java Programming Winner'}, 
	{galleryimage: 'images/gallery/award_15.jpg', gallerythumb: 'images/gallery/thumbs/award_15_thumb.jpg', gallerycaption: '2017 BPA SLC: Fifth Place Computer Programming Concepts (Open Event) Winner'}, 
	{galleryimage: 'images/gallery/award_16.jpg', gallerythumb: 'images/gallery/thumbs/award_16_thumb.jpg', gallerycaption: '2017 Skills USA District Conference: Overall First Place Computer Programming Winner'}, 
	{galleryimage: 'images/gallery/award_21.jpg', gallerythumb: 'images/gallery/thumbs/award_21_thumb.jpg', gallerycaption: '2016 BPA SLC: Fourth Place Java Programming Winner'}, 
	{galleryimage: 'images/gallery/award_22.jpg', gallerythumb: 'images/gallery/thumbs/award_22_thumb.jpg', gallerycaption: '2016 BPA SLC: Fifth Place Fundamentals of Web Design Winner'}, 
	{galleryimage: 'images/gallery/award_23.jpg', gallerythumb: 'images/gallery/thumbs/award_23_thumb.jpg', gallerycaption: '2016 Skills USA District Conference: Web Design Participant'}, 
	{galleryimage: 'images/gallery/award_24.jpg', gallerythumb: 'images/gallery/thumbs/award_24_thumb.jpg', gallerycaption: '2017-2018 Year Principals List: Term 1' }, 
	{galleryimage: 'images/gallery/award_25.jpg', gallerythumb: 'images/gallery/thumbs/award_25_thumb.jpg', gallerycaption: '2016-2017 Year Principals List: Term 4'}, 
	{galleryimage: 'images/gallery/award_26.jpg', gallerythumb: 'images/gallery/thumbs/award_26_thumb.jpg', gallerycaption: '2016-2017 Year Principals List: Term 3'}, 
	{galleryimage: 'images/gallery/award_27.jpg', gallerythumb: 'images/gallery/thumbs/award_27_thumb.jpg', gallerycaption: '2016-2017 Year Principals List: Term 2'}, 
	{galleryimage: 'images/gallery/award_28.jpg', gallerythumb: 'images/gallery/thumbs/award_28_thumb.jpg', gallerycaption: '2016-2017 Year Principals List: Term 1'}, 
	{galleryimage: 'images/gallery/award_29.jpg', gallerythumb: 'images/gallery/thumbs/award_29_thumb.jpg', gallerycaption: '2015-2016 Year Principals List: Term 4'}, 
	{galleryimage: 'images/gallery/award_30.jpg', gallerythumb: 'images/gallery/thumbs/award_30_thumb.jpg', gallerycaption: '2015-2016 Year Principals List: Term 3'}, 
	{galleryimage: 'images/gallery/award_31.jpg', gallerythumb: 'images/gallery/thumbs/award_31_thumb.jpg', gallerycaption: '2015-2016 Year Principals List: Term 2'}, 
	{galleryimage: 'images/gallery/award_32.jpg', gallerythumb: 'images/gallery/thumbs/award_32_thumb.jpg', gallerycaption: '2015-2016 Year Principals List: Term 1'}, 
	{galleryimage: 'images/gallery/award_33.jpg', gallerythumb: 'images/gallery/thumbs/award_33_thumb.jpg', gallerycaption: '2014-2015 Year Freshman Dean List Recipient'}, 
	{galleryimage: 'images/gallery/award_34.jpg', gallerythumb: 'images/gallery/thumbs/award_34_thumb.jpg', gallerycaption: '2014-2015 Freshman Dean List 3<sup>rd</sup> Quarter'}, 
	{galleryimage: 'images/gallery/award_35.jpg', gallerythumb: 'images/gallery/thumbs/award_35_thumb.jpg', gallerycaption: '2014-2015 Freshman Dean List 2<sup>nd</sup> Quarter'}, 
	{galleryimage: 'images/gallery/award_36.jpg', gallerythumb: 'images/gallery/thumbs/award_36_thumb.jpg', gallerycaption: '2014-2015 Freshman Dean List 1<sup>st</sup> Quarter'}, 
	{galleryimage: 'images/gallery/award_37.jpg', gallerythumb: 'images/gallery/thumbs/award_37_thumb.jpg', gallerycaption: '2014 Bear Award Winner For Demonstrating Core Values: Recommended by Lindsey Suprenant'}, 
	{galleryimage: 'images/gallery/award_38.jpg', gallerythumb: 'images/gallery/thumbs/award_38_thumb.jpg', gallerycaption: 'Appreciation Letter For <i>A Christmas Carol</i> Performance'}
];

